# config file for oh-my-zsh
...
ZSH_THEME="robbyrussell" #default
ZSH_THEME="agnoster" # very good
ZSH_THEME="amuse" # not bad
ZSH_THEME="agnoster" # very good
...
plugins=(git colored-man-pages colorize docker gradle jsontools kubectl microk8s minikube mvn yarn systemd)
...
